name: 'Azure OpenAI action'
description:
  'This action enables you to call the Azure OpenAI Service Chat Completions API
  within your GitHub Actions workflow.'
author: '@yuichielectric'

branding:
  icon: 'skip-forward'
  color: 'gray-dark'

inputs:
  api_url:
    description: 'The endpoint URL of Azure OpenAI Services'
    required: true
  deployment_id:
    description: 'The deployment ID of Azure OpenAI Services'
    required: true
  api_key:
    description: 'The API key to run Azure OpenAI Services'
    required: true
  system_prompt:
    description: 'The prompt to pass to the model'
    required: true
  input_text:
    description: 'The text to pass to the model'
    required: true

outputs:
  response:
    description: 'The response from Azure OpenAI Services'

runs:
  using: node20
  main: dist/index.js
