name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  api_url:
    description: 'The endpoint URL of Azure OpenAI Services'
    required: true
  deployment_id:
    description: 'The deployment ID of Azure OpenAI Services'
    required: true
  api_key:
    description: 'The API key to run Azure OpenAI Services'
    required: true
  prompt:
    description: 'The prompt to pass to the model'
    required: true

# Define your outputs here.
outputs:
  response:
    description: 'The response from Azure OpenAI Services'

runs:
  using: node20
  main: dist/index.js
